### ISSUE TITLE
How to avoid duplicates?

### ISSUE THREAD

**Issue by tek0011** [badgerious/puppet-windows-env#10]
How can I avoid duplicates on prepend?

			`# Adds %M2_HOME%\bin to the PATH
			windows_env {'addmavenpath':
				ensure      => present,
				mergemode   => prepend,
				variable    => 'PATH',
				value       => '%M2_HOME%\bin',
			}	 `

`C:\Users\Administrator>echo %PATH%
C:\PROGRA~1\apache-maven-3x\bin;C:\PROGRA~1\Java\jdk1.8.0_40\bin;C:\PROGRA~1\apache-maven-3x\bin;C:\PROGRA~1\apache-maven-3x\bin;C:\PROGRA~1\apache-maven-3x\bin;C:\PROGRA~1\ap
ache-maven-3x\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Pupp
et Labs\Puppet\bin;C:\Program Files (x86)\Dell\Enterprise Manager\msagui`

**Comment by tek0011** [comment]
Its duplicating it it on each run

**Comment by badgerious** [comment]
Hmm, seems like it's comparing unexpanded to expanded variables... Can you provide windows_env and ruby version? I'll take a look tomorrow.

**Comment by tek0011** [comment]
Looks to be Ruby 1.8.7 and windows_env 2.2.0

P.S.  You aren't out of MN are you?

**Comment by tek0011** [comment]
Side note.  I am not actually sure now it is an issue.  It's happening only on one server, and I can't reproduce it.  I'll keep trying.

**Comment by tek0011** [comment]
yep.  dont worry about this.  Issue isnt on your side.  something else was duplicating the paths.
