### ISSUE TITLE
Values with trailing slash do not include trailing slash

### ISSUE THREAD

**Issue by fivetanley** [badgerious/puppet-windows-env#15]
Hi! I'm pretty new to systems administration on windows. Your module has been a great help so far and I wanted to thank you for that!

I need to set an environment variable so that a bat file provided by Visual Studio 2008 can run. This bat script relies on the `VS90COMNTOOLS` value being set correctly. This configuration should work correctly, but doesn't.

```puppet
  windows_env { 'visual studio environment variables':
    ensure    => present,
    variable  => 'VS90COMNTOOLS',
    value     => 'C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\Common7\\Tools\\',
    mergemode => 'clobber'
  }~>
```

Where I expect `%VS90COMNTOOLS%` to equal `C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\Tools\`, it is instead `C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\Tools` (note the missing trailing slash). I may also be escaping the puppet string incorrectly, but I'm not sure.

Thanks for your time!

**Comment by badgerious** [comment]
If you use single quotes, you don't need to escape the backslash. Indeed, a quick test (with `puppet apply`) and your manifest gives me double backslashes (including a trailing double backslash):

```
C:\Users\Administrator>echo %VS90COMNTOOLS%
C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\Common7\\Tools\\
```

Switching to double quotes for the `value => ...` parameter gives me:

```
C:\Users\Administrator>echo %VS90COMNTOOLS%
C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\Tools\
```

The behavior you're seeing seems odd...

**Comment by badgerious** [comment]
I'm going to close this due to inactivity. Give it a prod if you think there's still an issue.
