### ISSUE TITLE
Upcoming Puppet 4 / Ruby 2.1.5 Registry compatibility changes

### ISSUE THREAD

**Issue by Iristyle** [badgerious/puppet-windows-env#8]
As part of making Puppet 4 compatible with Ruby 2.1.5, we have discovered a couple of bugs inside Ruby that will affect your module.  The two primary issues are:

* When enumerating keys with `#each_key` / `#keys` or values with `#each_value` / `#values`, Ruby will take a `UTF-16LE` string and [roundtrip it through the local codepage unnecessarily](https://github.com/ruby/ruby/blob/v2_1_5/ext/win32/lib/win32/registry.rb#L361-L367), which may cause encoding exceptions.  Our prime example of this is when a Unicode en-dash `U+2013` appears in a registry value, and the local codepage is `IBM437`, which has no equivalent character.  This is just one of many potential examples that may trigger this behavior.  NOTE: Normal registry reads of a value at a particular key are not problematic - the bad behavior is only triggered during enumeration.  We have not yet filed this bug with Ruby.
* When using the `#delete_key` and `#delete_value` methods, Ruby is passing wide character `UTF-16LE` strings to [ANSI APIs](https://github.com/ruby/ruby/blob/v2_1_5/ext/win32/lib/win32/registry.rb#L225-L226).  We have filed this bug with Ruby at https://bugs.ruby-lang.org/issues/10820

There are additional technical details that can be found in [PUP-3837](https://tickets.puppetlabs.com/browse/PUP-3837), the ticket we're using to track changes that we've made to Puppet.  Our resolution for these issues was merged to Puppet at https://github.com/puppetlabs/puppet/commit/c610cd01eeef3fafa7aa2761a3435dd6c1b0d8d4

We don't have Puppet 4 builds released yet, but keep an eye on https://groups.google.com/forum/#!forum/puppet-announce

I have identified issues with the code in this module that will require some updating to ensure it maintains compatibility with both existing Puppet releases and the upcoming releases. I'm getting in touch with you now, so that you're not caught off guard, and so that your module is ready to go by the time 4.0 ships.

Issues:

* `delete_value` is called at https://github.com/badgerious/puppet-windows-env/blob/master/lib/puppet/provider/windows_env/windows_env.rb#L196 and should instead use an internal definition for the `RegDeleteValueW` API call like we've done inside Puppet.
* You might want to also verify the module by hand using a Ruby 2.1.5 runtime.  To do this requires modifying `registry.rb`, present at `c:\tools\ruby215\lib\ruby\2.1.0\win32\registry.rb` in my install.  Some simple warnings may be emitted in several locations where problematic behavior can occur.  Then you can exercise your module / run specs for a full validation.

    * https://github.com/ruby/ruby/blob/v2_1_5/ext/win32/lib/win32/registry.rb#L815 should have `puts "BUG: RegDeleteValue called with #{name} against #{@keyname}"`
    * https://github.com/ruby/ruby/blob/v2_1_5/ext/win32/lib/win32/registry.rb#L836 and https://github.com/ruby/ruby/blob/v2_1_5/ext/win32/lib/win32/registry.rb#L841 should have `puts "BUG: RegDeleteKey called with #{name} against #{@keyname}"` added
    * https://github.com/ruby/ruby/blob/v2_1_5/ext/win32/lib/win32/registry.rb#L895 should have `puts "BUG: export_string triggered with #{str} to #{enc.to_s}"`
    * Optionally https://github.com/ruby/ruby/blob/v2_1_5/ext/win32/lib/win32/registry.rb#L363 can have `puts "BUG: expand_environ triggered with #{str}"` - while this behavior does trigger a string re-encode to the current codepage, we view it as less problematic as it requires `REG_MULTI_SZ` and environment variable expansion - where the values will typically be in the current codepage on a default system.

We will be making an announcement to the puppet-dev list shortly mentioning some of these upcoming changes.
https://groups.google.com/forum/#!forum/puppet-dev

Let me know if you have any questions.

Thanks!

**Comment by Iristyle** [comment]
Also see #6 when we had to address similar issues.

**Comment by badgerious** [comment]
@Iristyle Thanks, as before, for the very detailed issue. Looking into making the suggested fixes.

**Comment by badgerious** [comment]
Will wait for Puppet 4 builds to test on before merging.

**Comment by Iristyle** [comment]
Left one comment for you on 41ae24e @badgerious.

**Comment by ferventcoder** [comment]
@badgerious Do you think this will be released soon?

**Comment by Iristyle** [comment]
thanks for the reminder @ferventcoder - I also just filed the enumeration issue with Ruby at https://bugs.ruby-lang.org/issues/11410

**Comment by badgerious** [comment]
@ferventcoder Slipped off the radar (clearly :) !). I need to put together a Puppet 4 test environment to give it a run and then I'll cut a release.

**Comment by ferventcoder** [comment]
@badgerious awesome, thank you

**Comment by ferventcoder** [comment]
`\o/` - https://forge.puppetlabs.com/badgerious/windows_env/changelog
Sweet! Thanks. I now have a dependency on this module coming with choco - https://github.com/chocolatey/puppet-chocolatey/pull/76

**Comment by badgerious** [comment]
@ferventcoder Cool. Based on the way you're using windows_env, you may want to have a look at #11, a long standing issue I've not bothered to address since no one has complained. But it might affect you here.
